// Generated by CoffeeScript 1.8.0
(function() {
  var Component, EventEmitter,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EventEmitter = (require('events')).EventEmitter;

  module.exports = Component = (function(_super) {
    __extends(Component, _super);

    function Component() {
      return Component.__super__.constructor.apply(this, arguments);
    }

    Component.prototype.setData = function() {};

    Component.prototype.buildTree = function() {
      this.children = [];
      if (this.treeCache == null) {
        this.treeCache = this.render();
      }
      return this.treeCache;
    };

    Component.prototype.renderInner = function(componentClass, data) {
      var component;
      component = new componentClass();
      component.setData(data);
      component.parent = this;
      this.children.push(component);
      return component.buildTree();
    };

    Component.prototype.update = function() {
      this.treeCache = null;
      this.emit('update');
      if (this.parent != null) {
        return this.parent.update();
      }
    };

    return Component;

  })(EventEmitter);

}).call(this);
