// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var ComponentNode, Mount;

  Mount = require('./Mount');

  module.exports = ComponentNode = (function() {
    ComponentNode.prototype.type = 'Widget';

    function ComponentNode(klass, attrs) {
      this.klass = klass;
      this.attrs = attrs;
    }

    ComponentNode.prototype.init = function() {
      this.component = new this.klass();
      this.component.setAttributes(this.attrs);
      this.mount = new Mount(this.component);
      return this.mount.create();
    };

    ComponentNode.prototype.update = function(old, dom) {
      if (old.klass !== this.klass) {
        return this.init();
      }
      this.component = old.component;
      this.mount = old.mount;
      this.component.setAttributes(this.attrs);
      return this.mount.dom;
    };

    ComponentNode.prototype.destroy = function(dom) {
      this.mount.unmount();
      return this.component.destroy();
    };

    return ComponentNode;

  })();

}).call(this);
