// Generated by CoffeeScript 1.8.0
(function() {
  var Component, createElement, diff, h, patch;

  diff = require('virtual-dom/diff');

  patch = require('virtual-dom/patch');

  createElement = require('virtual-dom/create-element');

  h = require('virtual-hyperscript');

  module.exports = Component = (function() {
    function Component() {}

    Component.prototype.setData = function() {};

    Component.prototype.buildTree = function() {
      this.children = [];
      if (this.treeCache == null) {
        this.treeCache = this.render();
      }
      return this.treeCache;
    };

    Component.prototype.renderInner = function(componentClass, data) {
      var component;
      component = new componentClass();
      component.setData(data);
      component.parent = this;
      this.children.push(component);
      return component.buildTree();
    };

    Component.prototype.update = function() {
      this.treeCache = null;
      if (this.parent != null) {
        return this.parent.update();
      }
    };

    return Component;

  })();

}).call(this);
