// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var Component, ComponentNode, EventEmitter, assign, h, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  h = require('virtual-hyperscript');

  assign = (_ref = Object.assign) != null ? _ref : require('object-assign');

  EventEmitter = (require('events')).EventEmitter;

  ComponentNode = require('./ComponentNode');

  module.exports = Component = (function(_super) {
    __extends(Component, _super);

    function Component(attrs) {
      this.setAttributes(attrs);
      this.onInit();
    }

    Component.prototype.setAttributes = function(attrs) {
      assign(this, attrs);
      return this.emit('update');
    };

    Component.prototype.destroy = function() {
      return this.onDestroy();
    };

    Component.prototype.update = function() {
      return this.emit('update');
    };

    Component.prototype.render = function() {
      return h('div');
    };

    Component.prototype.onInit = function() {};

    Component.prototype.onDestroy = function() {};

    Component.render = function(attrs) {
      return new ComponentNode(this, attrs != null ? attrs : {});
    };

    return Component;

  })(EventEmitter);

}).call(this);
