// Generated by CoffeeScript 1.8.0
(function() {
  var createElement, diff, mount, patch;

  diff = require('virtual-dom/diff');

  patch = require('virtual-dom/patch');

  createElement = require('virtual-dom/create-element');

  module.exports = mount = function(component, target) {
    var element, query, tree;
    if (typeof target === 'string') {
      query = target;
      target = document.querySelector(query);
      if (target == null) {
        throw new Error("cannt find element: '" + query + "'");
      }
    }
    tree = component.buildTree();
    element = createElement(tree);
    target.parentElement.replaceChild(element, target);
    return component.on('update', function() {
      var newTree, patches;
      newTree = component.buildTree();
      patches = diff(tree, newTree);
      element = patch(element, patches);
      return tree = newTree;
    });
  };

}).call(this);
