// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var Mount, createDom, diff, patch;

  diff = require('virtual-dom/diff');

  patch = require('virtual-dom/patch');

  createDom = require('virtual-dom/create-element');

  module.exports = Mount = (function() {
    function Mount(component) {
      this.component = component;
      this.updateCallback = (function(_this) {
        return function() {
          return _this.update();
        };
      })(this);
    }

    Mount.prototype.update = function() {
      var newTree, patches;
      newTree = this.component.render();
      patches = diff(this.tree, newTree);
      this.dom = patch(this.dom, patches);
      return this.tree = newTree;
    };

    Mount.prototype.mount = function(placeholder) {
      var parent;
      this.create();
      parent = placeholder.parentElement;
      return parent.replaceChild(this.dom, placeholder);
    };

    Mount.prototype.create = function() {
      this.tree = this.component.render();
      this.dom = createDom(this.tree);
      this.component.on('update', this.updateCallback);
      return this.dom;
    };

    Mount.prototype.unmount = function() {
      return this.component.removeEventListener('update', this.updateCallback);
    };

    return Mount;

  })();

}).call(this);
